/**
 * 用户管理模块路由
 * 客户公司的主账户可以为员工创建子账户
 */

import { Router } from 'express'
import bcrypt from 'bcryptjs'
import { authenticate, requirePermission } from '../../middleware/auth.js'
import { getDatabase } from '../../config/database.js'

const router = Router()

// 密码强度验证
function validatePassword(password) {
  if (!password || password.length < 8) {
    return { valid: false, message: '密码长度不能少于8位' }
  }
  // 可选：增加复杂度要求
  // if (!/[A-Z]/.test(password)) {
  //   return { valid: false, message: '密码需要包含大写字母' }
  // }
  return { valid: true }
}

// 生成随机密码
function generateRandomPassword(length = 12) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%'
  let password = ''
  for (let i = 0; i < length; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return password
}

/**
 * 获取子账户列表
 * GET /api/users
 */
router.get('/', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const { page = 1, pageSize = 20, status, keyword } = req.query
    
    const offset = (parseInt(page) - 1) * parseInt(pageSize)
    const limit = parseInt(pageSize)
    
    // 构建查询条件
    let whereClause = 'WHERE pu.customer_id = $1 AND pu.status != $2'
    const params = [customerId, 'deleted']
    let paramIndex = 3
    
    if (status && status !== 'all') {
      whereClause += ` AND pu.status = $${paramIndex}`
      params.push(status)
      paramIndex++
    }
    
    if (keyword) {
      whereClause += ` AND (pu.username ILIKE $${paramIndex} OR pu.email ILIKE $${paramIndex} OR pu.display_name ILIKE $${paramIndex})`
      params.push(`%${keyword}%`)
      paramIndex++
    }
    
    // 查询总数
    const countResult = await db.prepare(`
      SELECT COUNT(*) as total
      FROM portal_users pu
      ${whereClause}
    `).get(...params)
    
    // 查询列表
    const users = await db.prepare(`
      SELECT 
        pu.id,
        pu.username,
        pu.email,
        pu.display_name,
        pu.phone,
        pu.role_id,
        pr.name as role_name,
        pu.status,
        pu.last_login_at,
        pu.created_at,
        pu.updated_at
      FROM portal_users pu
      LEFT JOIN portal_roles pr ON pu.role_id = pr.id
      ${whereClause}
      ORDER BY pu.created_at DESC
      LIMIT $${paramIndex} OFFSET $${paramIndex + 1}
    `).all(...params, limit, offset)
    
    res.json({
      errCode: 200,
      msg: 'success',
      data: {
        list: users,
        total: parseInt(countResult?.total || 0),
        page: parseInt(page),
        pageSize: limit
      }
    })
    
  } catch (error) {
    console.error('获取用户列表失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '获取用户列表失败',
      data: null
    })
  }
})

/**
 * 获取单个用户详情
 * GET /api/users/:id
 */
router.get('/:id', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const { id } = req.params
    
    const user = await db.prepare(`
      SELECT 
        pu.id,
        pu.username,
        pu.email,
        pu.display_name,
        pu.phone,
        pu.role_id,
        pr.name as role_name,
        pu.status,
        pu.last_login_at,
        pu.last_login_ip,
        pu.created_at,
        pu.updated_at
      FROM portal_users pu
      LEFT JOIN portal_roles pr ON pu.role_id = pr.id
      WHERE pu.id = $1 AND pu.customer_id = $2 AND pu.status != $3
    `).get(id, customerId, 'deleted')
    
    if (!user) {
      return res.status(404).json({
        errCode: 404,
        msg: '用户不存在',
        data: null
      })
    }
    
    res.json({
      errCode: 200,
      msg: 'success',
      data: user
    })
    
  } catch (error) {
    console.error('获取用户详情失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '获取用户详情失败',
      data: null
    })
  }
})

/**
 * 创建子账户
 * POST /api/users
 */
router.post('/', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const parentAccountId = req.customer.accountId
    
    const { username, email, password, displayName, phone, roleId } = req.body
    
    // 验证必填字段
    if (!username) {
      return res.status(400).json({
        errCode: 400,
        msg: '请输入用户名',
        data: null
      })
    }
    
    // 验证用户名格式
    if (!/^[a-zA-Z0-9_]{3,30}$/.test(username)) {
      return res.status(400).json({
        errCode: 400,
        msg: '用户名只能包含字母、数字和下划线，长度3-30位',
        data: null
      })
    }
    
    // 生成或验证密码
    let userPassword = password
    let isAutoGenerated = false
    
    if (!userPassword) {
      // 自动生成密码
      userPassword = generateRandomPassword()
      isAutoGenerated = true
    } else {
      // 验证密码强度
      const pwdValidation = validatePassword(userPassword)
      if (!pwdValidation.valid) {
        return res.status(400).json({
          errCode: 400,
          msg: pwdValidation.message,
          data: null
        })
      }
    }
    
    // 检查用户名是否已存在
    const existingUsername = await db.prepare(`
      SELECT id FROM portal_users 
      WHERE customer_id = $1 AND username = $2 AND status != $3
    `).get(customerId, username, 'deleted')
    
    if (existingUsername) {
      return res.status(400).json({
        errCode: 400,
        msg: '该用户名已被使用',
        data: null
      })
    }
    
    // 检查邮箱是否已存在（如果提供了邮箱）
    if (email) {
      const existingEmail = await db.prepare(`
        SELECT id FROM portal_users 
        WHERE customer_id = $1 AND email = $2 AND status != $3
      `).get(customerId, email, 'deleted')
      
      if (existingEmail) {
        return res.status(400).json({
          errCode: 400,
          msg: '该邮箱已被使用',
          data: null
        })
      }
    }
    
    // 验证角色是否存在（如果提供了）
    if (roleId) {
      const role = await db.prepare(`
        SELECT id FROM portal_roles 
        WHERE id = $1 AND customer_id = $2 AND status = $3
      `).get(roleId, customerId, 'active')
      
      if (!role) {
        return res.status(400).json({
          errCode: 400,
          msg: '指定的角色不存在',
          data: null
        })
      }
    }
    
    // 加密密码
    const passwordHash = await bcrypt.hash(userPassword, 10)
    
    // 创建用户
    const result = await db.prepare(`
      INSERT INTO portal_users 
      (parent_account_id, customer_id, username, email, password_hash, display_name, phone, role_id, created_by)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      RETURNING id
    `).get(
      parentAccountId,
      customerId,
      username,
      email || null,
      passwordHash,
      displayName || username,
      phone || null,
      roleId || null,
      parentAccountId
    )
    
    const responseData = {
      id: result.id,
      username,
      email,
      displayName: displayName || username
    }
    
    // 如果是自动生成的密码，返回给前端显示一次
    if (isAutoGenerated) {
      responseData.generatedPassword = userPassword
    }
    
    res.json({
      errCode: 200,
      msg: '用户创建成功',
      data: responseData
    })
    
  } catch (error) {
    console.error('创建用户失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '创建用户失败: ' + error.message,
      data: null
    })
  }
})

/**
 * 更新子账户
 * PUT /api/users/:id
 */
router.put('/:id', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const { id } = req.params
    const { email, displayName, phone, roleId, status } = req.body
    
    // 检查用户是否存在
    const existingUser = await db.prepare(`
      SELECT id, username FROM portal_users 
      WHERE id = $1 AND customer_id = $2 AND status != $3
    `).get(id, customerId, 'deleted')
    
    if (!existingUser) {
      return res.status(404).json({
        errCode: 404,
        msg: '用户不存在',
        data: null
      })
    }
    
    // 检查邮箱是否已被其他用户使用
    if (email) {
      const emailExists = await db.prepare(`
        SELECT id FROM portal_users 
        WHERE customer_id = $1 AND email = $2 AND id != $3 AND status != $4
      `).get(customerId, email, id, 'deleted')
      
      if (emailExists) {
        return res.status(400).json({
          errCode: 400,
          msg: '该邮箱已被其他用户使用',
          data: null
        })
      }
    }
    
    // 验证角色是否存在
    if (roleId) {
      const role = await db.prepare(`
        SELECT id FROM portal_roles 
        WHERE id = $1 AND customer_id = $2 AND status = $3
      `).get(roleId, customerId, 'active')
      
      if (!role) {
        return res.status(400).json({
          errCode: 400,
          msg: '指定的角色不存在',
          data: null
        })
      }
    }
    
    // 验证状态值
    const validStatuses = ['active', 'disabled']
    if (status && !validStatuses.includes(status)) {
      return res.status(400).json({
        errCode: 400,
        msg: '无效的状态值',
        data: null
      })
    }
    
    // 更新用户
    await db.prepare(`
      UPDATE portal_users 
      SET 
        email = COALESCE($1, email),
        display_name = COALESCE($2, display_name),
        phone = COALESCE($3, phone),
        role_id = COALESCE($4, role_id),
        status = COALESCE($5, status)
      WHERE id = $6 AND customer_id = $7
    `).run(
      email || null,
      displayName || null,
      phone || null,
      roleId || null,
      status || null,
      id,
      customerId
    )
    
    res.json({
      errCode: 200,
      msg: '用户更新成功',
      data: null
    })
    
  } catch (error) {
    console.error('更新用户失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '更新用户失败',
      data: null
    })
  }
})

/**
 * 删除子账户（软删除）
 * DELETE /api/users/:id
 */
router.delete('/:id', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const { id } = req.params
    
    // 检查用户是否存在
    const existingUser = await db.prepare(`
      SELECT id FROM portal_users 
      WHERE id = $1 AND customer_id = $2 AND status != $3
    `).get(id, customerId, 'deleted')
    
    if (!existingUser) {
      return res.status(404).json({
        errCode: 404,
        msg: '用户不存在',
        data: null
      })
    }
    
    // 软删除
    await db.prepare(`
      UPDATE portal_users 
      SET status = $1
      WHERE id = $2 AND customer_id = $3
    `).run('deleted', id, customerId)
    
    res.json({
      errCode: 200,
      msg: '用户已删除',
      data: null
    })
    
  } catch (error) {
    console.error('删除用户失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '删除用户失败',
      data: null
    })
  }
})

/**
 * 重置用户密码
 * POST /api/users/:id/reset-password
 */
router.post('/:id/reset-password', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const { id } = req.params
    const { newPassword } = req.body
    
    // 检查用户是否存在
    const existingUser = await db.prepare(`
      SELECT id, username FROM portal_users 
      WHERE id = $1 AND customer_id = $2 AND status != $3
    `).get(id, customerId, 'deleted')
    
    if (!existingUser) {
      return res.status(404).json({
        errCode: 404,
        msg: '用户不存在',
        data: null
      })
    }
    
    // 生成或使用指定密码
    let password = newPassword
    let isAutoGenerated = false
    
    if (!password) {
      password = generateRandomPassword()
      isAutoGenerated = true
    } else {
      const pwdValidation = validatePassword(password)
      if (!pwdValidation.valid) {
        return res.status(400).json({
          errCode: 400,
          msg: pwdValidation.message,
          data: null
        })
      }
    }
    
    // 加密密码
    const passwordHash = await bcrypt.hash(password, 10)
    
    // 更新密码
    await db.prepare(`
      UPDATE portal_users 
      SET password_hash = $1, password_changed_at = NOW(), login_attempts = 0, locked_until = NULL
      WHERE id = $2 AND customer_id = $3
    `).run(passwordHash, id, customerId)
    
    const responseData = {
      username: existingUser.username,
      message: '密码已重置'
    }
    
    if (isAutoGenerated) {
      responseData.newPassword = password
    }
    
    res.json({
      errCode: 200,
      msg: '密码重置成功',
      data: responseData
    })
    
  } catch (error) {
    console.error('重置密码失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '重置密码失败',
      data: null
    })
  }
})

/**
 * 切换用户状态（启用/禁用）
 * POST /api/users/:id/toggle-status
 */
router.post('/:id/toggle-status', authenticate, async (req, res) => {
  try {
    const db = getDatabase()
    const customerId = req.customer.customerId
    const { id } = req.params
    
    // 获取当前用户状态
    const user = await db.prepare(`
      SELECT id, status FROM portal_users 
      WHERE id = $1 AND customer_id = $2 AND status != $3
    `).get(id, customerId, 'deleted')
    
    if (!user) {
      return res.status(404).json({
        errCode: 404,
        msg: '用户不存在',
        data: null
      })
    }
    
    // 切换状态
    const newStatus = user.status === 'active' ? 'disabled' : 'active'
    
    await db.prepare(`
      UPDATE portal_users 
      SET status = $1
      WHERE id = $2 AND customer_id = $3
    `).run(newStatus, id, customerId)
    
    res.json({
      errCode: 200,
      msg: newStatus === 'active' ? '用户已启用' : '用户已禁用',
      data: { status: newStatus }
    })
    
  } catch (error) {
    console.error('切换用户状态失败:', error)
    res.status(500).json({
      errCode: 500,
      msg: '操作失败',
      data: null
    })
  }
})

export default router

